sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: smalltalk
before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
before_script:
  - wget http://selenium-release.storage.googleapis.com/3.11/selenium-server-standalone-3.11.0.jar
  - wget https://chromedriver.storage.googleapis.com/2.35/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - "java -Dwebdriver.chrome.driver=chromedriver -jar selenium-server-standalone-3.11.0.jar -port 4444 > /tmp/seleniumlog.&"
smalltalk:
  - Pharo64-alpha
  - Pharo-alpha
  - Pharo64-7.0
  - Pharo-7.0
  - Pharo64-6.1
  - Pharo-6.1
  - Pharo64-6.0
  - Pharo-6.0
  - Pharo-5.0
  - Pharo-4.0
  - Squeak-5.1
  - GemStone-3.3.3
  - GemStone-3.2.15
  - GemStone-3.1.0.6
matrix:
  allow_failures:
    - smalltalk: Pharo64-alpha
    - smalltalk: Pharo-alpha
    - smalltalk: Pharo64-7.0
    - smalltalk: Pharo-7.0
    - smalltalk: Pharo64-6.1
    - smalltalk: Pharo64-6.0
